events {
    worker_connections 1024; # Maximum number of connections per process
}

http {
    # Sets the bounding box
    limit_req_zone $binary_remote_addr zone=apilimit:10m rate=10r/s;

    # Define the upstream block for the default backend service (sentiment-apis-v1)
    upstream sentiment-apis-v1 {
        server sentiment-prediction-1-api:8000;
    }

    # Define the upstream block for the backend service for group 2 (sentiment-prediction-2-api)
    upstream sentiment-api-v2 {
        server sentiment-prediction-2-api:8000;
    }

    # According to the content of the X-Experiment-Group-HTTP header, map the traffic to the corresponding backend service
    map $http_x_experiment_group $backend {
        default sentiment-apis-v1; # Default backend service
        "debug" sentiment-api-v2;  # Backend service for group 2
    }  

    # Define the virtual server
    server {
        listen 80;
        server_name localhost; 

        # redirect all HTTP requests to HTTPS
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name localhost;

        # Paths to SSL certificates inside the Nginx container
        ssl_certificate /etc/nginx/certs/nginx.crt;
        ssl_certificate_key /etc/nginx/certs/nginx.key;
       
        # SSL protocols and siphers
        ssl_protocols TLSv1.2 TLSv1.3; # only allow modern versions of TLS
        ssl_ciphers HIGH:!aNULL:!MD5; # list of allowed cipher suites
        ssl_prefer_server_ciphers on; # prefer server ciphers

        # All requests that start with /predict/ will be handled here
        location /predict {
            auth_basic "API Access Protected"; # Message displayed to the user
            auth_basic_user_file /etc/nginx/.htpasswd; # Path to the .htpasswd file in the container

            # Applies the limitation to the 'location/predict' block
            limit_req zone=apilimit burst=5 nodelay;

            # proxy_pass: Redirects the request to the backend service
            proxy_pass http://$backend;
            

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        
        }

        location /nginx_status {
            stub_status on; # Activates the module stub status
            access_log off; # do not log access to this endpoint
            allow 127.0.0.1; # allow access only from localhost
            allow 172.18.0.0/16; # allow access from the docker network
            deny all; # Blocks all other access
        }
    }
}
